copyright = "Arithmatics"
baseURL = "https://arithmatics.com/"
canonifyurls = true
languageCode = "en-us"
defaultContentLanguage = "en"

theme = "honokichi"
publishDir = "docs"

[languages]

  [languages.en]
  baseURL = "https://arithmatics.com/"
  languageName = "English"
  title = "Arithmatics"

  [languages.ja]
  baseURL = "https://ja.arithmatics.com/"
  languageName = "Japanese"
  title = "算術演算解析譜工房"

[params.social]
  twitter_id = "@arithmatics"
  github = "arithmatics-factory"

