baseURL = "https://www.arithmatics.com/"
canonifyurls = true
languageCode = "en-us"
title = "My New Hugo Site"
theme = "honokichi"
publishDir = "docs"

[params.social]
  twitter_id = "@arithmatics"
  github = "arithmatics-factory"
